services:
  api:
    image: ghcr.io/${IMAGE_OWNER:-stefano-mt}/viva-inteligencia-api:${IMAGE_TAG:-latest}
    build: !reset null

  web:
    image: ghcr.io/${IMAGE_OWNER:-stefano-mt}/viva-inteligencia-web:${IMAGE_TAG:-latest}
    build: !reset null
